name: Build and Scan Docker Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/getschwifty:${IMAGE_TAG} .
          docker push ${{ secrets.DOCKER_USERNAME }}/getschwifty:${IMAGE_TAG}
          docker image tag ${{ secrets.DOCKER_USERNAME }}/getschwifty:${IMAGE_TAG} ${{ secrets.DOCKER_USERNAME }}/getschwifty:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/getschwifty:latest
      - name: Scan Docker image for vulnerabilities
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          ./bin/trivy image --severity HIGH,CRITICAL --exit-code 1 ${{ secrets.DOCKER_USERNAME }}/getschwifty:${IMAGE_TAG}
      - name: Push Docker image to Docker Hub
        if: success() # Only push if the scan is successful
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/getschwifty:${IMAGE_TAG}

